save_root: ./training_datas
aux_dir: aux
base_dir: base 
process_dataset: [svpp]
workers: 16
datasets:
    svpp:
        data_root: /mnt/fillipo/yaowei/svpp_release_data/svpp_data
        process_number: 20
        segmentator_s: 0.1
        segmentator_k: 100
        resplit_aug: True






    